"use client";
import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { OverrideForm } from "./OverrideForm";

export type ReviewItem = { question_id: string; question: string; answer: string; model_answer: string; max_marks: number; score: null | { source: string; marks: number; reason: string | null; needs_review: boolean; details: Record<string, unknown> | null } };
export function AttemptReview({ attemptId, items }: { attemptId: string; items: ReviewItem[] }) {
  const [reviewOnly, setReviewOnly] = useState(false); const visible = reviewOnly ? items.filter((item) => item.score?.needs_review || !item.score) : items;
  async function regrade(questionId: string) { await fetch(`/api/admin/results/${attemptId}/regrade`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question_id: questionId }) }); }
  const phrases = (value: unknown) => Array.isArray(value) ? value.filter((entry): entry is string => typeof entry === "string").join(", ") : "";
  return <section><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={reviewOnly} onChange={(event) => setReviewOnly(event.target.checked)} /> Needs review only</label>{items.some((item) => !item.score) ? <p className="border-l-4 border-warning bg-warning-tint p-3">{items.filter((item) => !item.score).length} questions not graded.</p> : null}{visible.map((item) => { const details = item.score?.details; return <article className="my-5 space-y-3 border border-line bg-surface p-5" key={item.question_id}><h2 className="font-bold">{item.question}</h2><p><strong>Candidate answer:</strong> {item.answer || "No answer"}</p><p><strong>Model answer:</strong> {item.model_answer}</p><p><strong>Score:</strong> {item.score ? `${item.score.marks} / ${item.max_marks}` : "Not graded"}{item.score?.source === "override" ? " — Override" : ""}</p>{item.score?.reason ? <p>{item.score.reason}</p> : null}{details?.candidate_meaning_english ? <p><strong>Meaning in English:</strong> {String(details.candidate_meaning_english)}</p> : null}{details ? <dl className="grid gap-1 text-sm"><dt className="font-bold">Matched points</dt><dd>{phrases(details.matched_points) || "None"}</dd><dt className="font-bold">Missing points</dt><dd>{phrases(details.missing_points) || "None"}</dd><dt className="font-bold">Incorrect claims</dt><dd>{phrases(details.incorrect_claims) || "None"}</dd><dt className="font-bold">Confidence</dt><dd>{typeof details.confidence === "number" ? details.confidence : "—"}</dd><dt className="font-bold">Model / prompt</dt><dd>{String(details.model ?? "—")} / {String(details.prompt_version ?? "—")}</dd></dl> : null}<OverrideForm attemptId={attemptId} questionId={item.question_id} maxMarks={item.max_marks} /><Button variant="secondary" onClick={() => void regrade(item.question_id)}>Regrade</Button></article>; })}</section>;
}
